# Generated by Django 5.2.3 on 2025-06-23 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='patient',
            name='attending_doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Лечащий врач'),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact',
            field=models.CharField(default=1, max_length=255, verbose_name='Контакты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
    ]
